apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
  selector:
    app: grpc-server
